name: deploy

on:
  push:
    branches: [main]

jobs:
  build:

    runs-on: self-hosted

    steps:
    - uses: actions/checkout@v2
    - name: Setup .NET
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 6.0.x
    - name: Restore dependencies
      run: dotnet restore
    - name: Build dotnet
      run: dotnet build --no-restore
    - name: Build css
      run: npm run build:css
    
  deploy:
    
    runs-on: self-hosted
    env:
      DOTNET-PID: pgrep dotnet

    steps:
    - name: Kill running server if present
      if: env.DOTNET-PID != 0
      run: kill `pgrep dotnet`
    
    - name: Publish app
      run: dotnet publish
    
    - name: Deploy
      run: nohup dotnet ~/bin/Debug/net6.0/publish/fictionsplash.dll &